name: conan-package

on:
  push:
    paths:
      - 'src/**'
      - 'test_package/**'
      - 'include/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'conandata.yml'
      - 'CMakeLists.txt'
      - '.github/workflows/conan-package.yml'
      - '.github/workflows/requirements*'
      - '.gitattributes'
    branches:
        - main
        - 'CURA-*'
        - 'PP-*'
        - '[0-9].[0-9]*'
        - '[0-9].[0-9][0-9]*'

jobs:
  conan-package:
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/conan-package.yml@main
    secrets: inherit
