name: conan-package

# Exports the recipe, sources and binaries for Mac, Windows and Linux and upload these to the server such that these can
# be used downstream.
#
# It should run on pushes against main or CURA-* branches, but it will only create the binaries for main and release branches

on:
    push:
        paths:
            - 'src/**'
            - 'test_package/**'
            - 'include/**'
            - 'cmake/**'
            - 'conanfile.py'
            - 'CMakeLists.txt'
            - '.github/workflows/conan-package.yml'
            - '.github/workflows/requirements*'
            - 'conandata.yml'
            - '.gitattributes'
        branches:
            - 'main'
            - 'CURA-*'
            - '[1-9]+.[0-9]+'

jobs:
    conan-recipe-version:
        uses: lulzbot3d/CuraLE/.github/workflows/conan-recipe-version.yml@main
        with:
            project_name: arcusle

    conan-package-export:
        needs: [ conan-recipe-version ]
        uses: lulzbot3d/CuraLE/.github/workflows/conan-recipe-export.yml@main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
            runs_on: 'ubuntu-20.04'
            python_version: '3.10.x'
            conan_logging_level: 'info'
        secrets: inherit

    conan-package-create-macos:
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        needs: [ conan-recipe-version, conan-package-export ]

        uses: lulzbot3d/CuraLE/.github/workflows/conan-package-create.yml@main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            runs_on: 'macos-11'
            python_version: '3.10.x'
            conan_logging_level: 'info'
        secrets: inherit

    conan-package-create-windows:
        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && inputs.create_binaries_windows) }}
        needs: [ conan-recipe-version, conan-package-export ]

        uses: lulzbot3d/CuraLE/.github/workflows/conan-package-create.yml@main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            runs_on: 'windows-2022'
            python_version: '3.10.x'
            conan_config_branch: ''
            conan_logging_level: 'info'
        secrets: inherit

    conan-package-create-linux:
        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && inputs.create_binaries_linux) }}
        needs: [ conan-recipe-version, conan-package-export ]

        uses: lulzbot3d/CuraLE/.github/workflows/conan-package-create.yml@main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            runs_on: 'ubuntu-20.04'
            python_version: '3.10.x'
            conan_logging_level: 'info'
        secrets: inherit