---
name: conan-package

# Exports the recipe, sources and binaries for Mac, Windows and Linux and upload these to the server such that these can
# be used downstream.
#
# It should run on pushes against main or CURA-* branches, but it will only create the binaries for main and release branches

on:
    workflow_dispatch:
        inputs:
            # FIXME: Not yet implemented
            conan_id:
                required: false
                type: string
                description: 'The full conan package ID, e.g. "arcusle/1.2.3@lulzbot/stable"'
            create_latest_alias:
                required: true
                default: false
                type: boolean
                description: 'Create latest alias'
            create_binaries_windows:
                required: true
                default: false
                type: boolean
                description: 'create binaries Windows'
            create_binaries_linux:
                required: true
                default: false
                type: boolean
                description: 'create binaries Linux'
            create_binaries_macos:
                required: true
                default: false
                type: boolean
                description: 'create binaries Macos'

    push:
        paths:
            - 'src/**'
            - 'test_package/**'
            - 'include/**'
            - 'cmake/**'
            - 'conanfile.py'
            - 'CMakeLists.txt'
            - '.github/workflows/conan-package.yml'
            - '.github/workflows/requirements*'
            - 'conandata.yml'
            - '.gitattributes'
        branches:
            - 'main'
            - 'CURA-*'
            - '[1-9]+.[0-9]+'
        tags:
            - '[1-9]+.[0-9]+.[0-9]*'

jobs:
    conan-recipe-version:
        uses: lulzbot3d/CuraLE/.github/workflows/conan-recipe-version.yml@main
        with:
            project_name: arcusle

    conan-package-export:
        needs: [ conan-recipe-version ]
        uses: lulzbot3d/CuraLE/.github/workflows/conan-recipe-export.yml@main
        with:
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            recipe_id_latest: ${{ needs.conan-recipe-version.outputs.recipe_id_latest }}
            runs_on: 'ubuntu-20.04'
            python_version: '3.10.x'
            conan_logging_level: 'info'
        secrets: inherit

    conan-package-create-windows:
        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && inputs.create_binaries_windows) }}
        needs: [ conan-recipe-version, conan-package-export ]

        uses: lulzbot3d/CuraLE/.github/workflows/conan-package-create.yml@main
        with:
            project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            build_id: 4
            runs_on: 'windows-2022'
            python_version: '3.11.x'
            conan_config_branch: ''
            conan_logging_level: 'info'
        secrets: inherit

    conan-package-create-macos:
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        needs: [ conan-recipe-version, conan-package-export ]

        uses: lulzbot3d/CuraLE/.github/workflows/conan-package-create.yml@main
        with:
            project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            build_id: 3
            runs_on: 'macos-11'
            python_version: '3.11.x'
            conan_logging_level: 'info'
        secrets: inherit
        
    conan-package-create-linux-modern:
        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && inputs.create_binaries_linux) }}
        needs: [ conan-recipe-version, conan-package-export ]

        uses: lulzbot3d/CuraLE/.github/workflows/conan-package-create.yml@main
        with:
            project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            build_id: 2
            runs_on: 'ubuntu-22.04'
            python_version: '3.11.x'
            conan_logging_level: 'info'
        secrets: inherit

    conan-package-create-linux:
        if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || (github.event_name == 'workflow_dispatch' && inputs.create_binaries_linux) }}
        needs: [ conan-recipe-version, conan-package-export ]

        uses: lulzbot3d/CuraLE/.github/workflows/conan-package-create.yml@main
        with:
            project_name: ${{ needs.conan-recipe-version.outputs.project_name }}
            recipe_id_full: ${{ needs.conan-recipe-version.outputs.recipe_id_full }}
            build_id: 1
            runs_on: 'ubuntu-20.04'
            python_version: '3.11.x'
            conan_logging_level: 'info'
        secrets: inherit

